var express = require("express");
var router = express.Router();
var userCtrl = require("../../controller/admin/userController");
var mw = require("../../Middleware/admin");
router.get("", mw.hasLogin, userCtrl.getlistUser);
router.get("/add", mw.hasLogin, userCtrl.getpageAdd);
router.post("/add", mw.hasLogin, userCtrl.adduser);
router.get("/del/:id", mw.hasLogin, userCtrl.deluser);
router.get("/edit/:id", mw.hasLogin, userCtrl.getuserEdit);
router.post("/edit/done", mw.hasLogin, userCtrl.editUser);
router.get("/logout", mw.hasLogin, userCtrl.logout);
module.exports = router;
